[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure images are handled correctly
[[headers]]
  for = "*/ressources/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
